/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsAnvayAvillasKongaraKalanRouteImport } from './routes/projects.anvay-avillas-kongara-kalan'
import { Route as ProjectsAutumnVillasMaheshwaramRouteImport } from './routes/projects.autumn-villas-maheshwaram'
import { Route as ProjectsConstellaVillasTukkugudaRouteImport } from './routes/projects.constella-villas-tukkuguda'
import { Route as ProjectsKavuriForestNestImmagudaRouteImport } from './routes/projects.kavuri-forest-nest-immaguda'
import { Route as ProjectsKavuriHillsLemonLeafTukkugudaRouteImport } from './routes/projects.kavuri-hills-lemon-leaf-tukkuguda'
import { Route as ProjectsRiddhiLaxmanCountyTukkugudaRouteImport } from './routes/projects.riddhi-laxman-county-tukkuguda'
import { Route as ProjectsVertexFlorenzaTukkugudaRouteImport } from './routes/projects.vertex-florenza-tukkuguda'
import { Route as ProjectsVertexVivaCalistaTukkugudaRouteImport } from './routes/projects.vertex-viva-calista-tukkuguda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsAnvayAvillasKongaraKalanRoute =
  ProjectsAnvayAvillasKongaraKalanRouteImport.update({
    id: '/projects/anvay-avillas-kongara-kalan',
    path: '/projects/anvay-avillas-kongara-kalan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAutumnVillasMaheshwaramRoute =
  ProjectsAutumnVillasMaheshwaramRouteImport.update({
    id: '/projects/autumn-villas-maheshwaram',
    path: '/projects/autumn-villas-maheshwaram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsConstellaVillasTukkugudaRoute =
  ProjectsConstellaVillasTukkugudaRouteImport.update({
    id: '/projects/constella-villas-tukkuguda',
    path: '/projects/constella-villas-tukkuguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsKavuriForestNestImmagudaRoute =
  ProjectsKavuriForestNestImmagudaRouteImport.update({
    id: '/projects/kavuri-forest-nest-immaguda',
    path: '/projects/kavuri-forest-nest-immaguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsKavuriHillsLemonLeafTukkugudaRoute =
  ProjectsKavuriHillsLemonLeafTukkugudaRouteImport.update({
    id: '/projects/kavuri-hills-lemon-leaf-tukkuguda',
    path: '/projects/kavuri-hills-lemon-leaf-tukkuguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsRiddhiLaxmanCountyTukkugudaRoute =
  ProjectsRiddhiLaxmanCountyTukkugudaRouteImport.update({
    id: '/projects/riddhi-laxman-county-tukkuguda',
    path: '/projects/riddhi-laxman-county-tukkuguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsVertexFlorenzaTukkugudaRoute =
  ProjectsVertexFlorenzaTukkugudaRouteImport.update({
    id: '/projects/vertex-florenza-tukkuguda',
    path: '/projects/vertex-florenza-tukkuguda',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsVertexVivaCalistaTukkugudaRoute =
  ProjectsVertexVivaCalistaTukkugudaRouteImport.update({
    id: '/projects/vertex-viva-calista-tukkuguda',
    path: '/projects/vertex-viva-calista-tukkuguda',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/anvay-avillas-kongara-kalan': typeof ProjectsAnvayAvillasKongaraKalanRoute
  '/projects/autumn-villas-maheshwaram': typeof ProjectsAutumnVillasMaheshwaramRoute
  '/projects/constella-villas-tukkuguda': typeof ProjectsConstellaVillasTukkugudaRoute
  '/projects/kavuri-forest-nest-immaguda': typeof ProjectsKavuriForestNestImmagudaRoute
  '/projects/kavuri-hills-lemon-leaf-tukkuguda': typeof ProjectsKavuriHillsLemonLeafTukkugudaRoute
  '/projects/riddhi-laxman-county-tukkuguda': typeof ProjectsRiddhiLaxmanCountyTukkugudaRoute
  '/projects/vertex-florenza-tukkuguda': typeof ProjectsVertexFlorenzaTukkugudaRoute
  '/projects/vertex-viva-calista-tukkuguda': typeof ProjectsVertexVivaCalistaTukkugudaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/anvay-avillas-kongara-kalan': typeof ProjectsAnvayAvillasKongaraKalanRoute
  '/projects/autumn-villas-maheshwaram': typeof ProjectsAutumnVillasMaheshwaramRoute
  '/projects/constella-villas-tukkuguda': typeof ProjectsConstellaVillasTukkugudaRoute
  '/projects/kavuri-forest-nest-immaguda': typeof ProjectsKavuriForestNestImmagudaRoute
  '/projects/kavuri-hills-lemon-leaf-tukkuguda': typeof ProjectsKavuriHillsLemonLeafTukkugudaRoute
  '/projects/riddhi-laxman-county-tukkuguda': typeof ProjectsRiddhiLaxmanCountyTukkugudaRoute
  '/projects/vertex-florenza-tukkuguda': typeof ProjectsVertexFlorenzaTukkugudaRoute
  '/projects/vertex-viva-calista-tukkuguda': typeof ProjectsVertexVivaCalistaTukkugudaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/anvay-avillas-kongara-kalan': typeof ProjectsAnvayAvillasKongaraKalanRoute
  '/projects/autumn-villas-maheshwaram': typeof ProjectsAutumnVillasMaheshwaramRoute
  '/projects/constella-villas-tukkuguda': typeof ProjectsConstellaVillasTukkugudaRoute
  '/projects/kavuri-forest-nest-immaguda': typeof ProjectsKavuriForestNestImmagudaRoute
  '/projects/kavuri-hills-lemon-leaf-tukkuguda': typeof ProjectsKavuriHillsLemonLeafTukkugudaRoute
  '/projects/riddhi-laxman-county-tukkuguda': typeof ProjectsRiddhiLaxmanCountyTukkugudaRoute
  '/projects/vertex-florenza-tukkuguda': typeof ProjectsVertexFlorenzaTukkugudaRoute
  '/projects/vertex-viva-calista-tukkuguda': typeof ProjectsVertexVivaCalistaTukkugudaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/projects/anvay-avillas-kongara-kalan'
    | '/projects/autumn-villas-maheshwaram'
    | '/projects/constella-villas-tukkuguda'
    | '/projects/kavuri-forest-nest-immaguda'
    | '/projects/kavuri-hills-lemon-leaf-tukkuguda'
    | '/projects/riddhi-laxman-county-tukkuguda'
    | '/projects/vertex-florenza-tukkuguda'
    | '/projects/vertex-viva-calista-tukkuguda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/projects/anvay-avillas-kongara-kalan'
    | '/projects/autumn-villas-maheshwaram'
    | '/projects/constella-villas-tukkuguda'
    | '/projects/kavuri-forest-nest-immaguda'
    | '/projects/kavuri-hills-lemon-leaf-tukkuguda'
    | '/projects/riddhi-laxman-county-tukkuguda'
    | '/projects/vertex-florenza-tukkuguda'
    | '/projects/vertex-viva-calista-tukkuguda'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/projects/anvay-avillas-kongara-kalan'
    | '/projects/autumn-villas-maheshwaram'
    | '/projects/constella-villas-tukkuguda'
    | '/projects/kavuri-forest-nest-immaguda'
    | '/projects/kavuri-hills-lemon-leaf-tukkuguda'
    | '/projects/riddhi-laxman-county-tukkuguda'
    | '/projects/vertex-florenza-tukkuguda'
    | '/projects/vertex-viva-calista-tukkuguda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsAnvayAvillasKongaraKalanRoute: typeof ProjectsAnvayAvillasKongaraKalanRoute
  ProjectsAutumnVillasMaheshwaramRoute: typeof ProjectsAutumnVillasMaheshwaramRoute
  ProjectsConstellaVillasTukkugudaRoute: typeof ProjectsConstellaVillasTukkugudaRoute
  ProjectsKavuriForestNestImmagudaRoute: typeof ProjectsKavuriForestNestImmagudaRoute
  ProjectsKavuriHillsLemonLeafTukkugudaRoute: typeof ProjectsKavuriHillsLemonLeafTukkugudaRoute
  ProjectsRiddhiLaxmanCountyTukkugudaRoute: typeof ProjectsRiddhiLaxmanCountyTukkugudaRoute
  ProjectsVertexFlorenzaTukkugudaRoute: typeof ProjectsVertexFlorenzaTukkugudaRoute
  ProjectsVertexVivaCalistaTukkugudaRoute: typeof ProjectsVertexVivaCalistaTukkugudaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects/anvay-avillas-kongara-kalan': {
      id: '/projects/anvay-avillas-kongara-kalan'
      path: '/projects/anvay-avillas-kongara-kalan'
      fullPath: '/projects/anvay-avillas-kongara-kalan'
      preLoaderRoute: typeof ProjectsAnvayAvillasKongaraKalanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/autumn-villas-maheshwaram': {
      id: '/projects/autumn-villas-maheshwaram'
      path: '/projects/autumn-villas-maheshwaram'
      fullPath: '/projects/autumn-villas-maheshwaram'
      preLoaderRoute: typeof ProjectsAutumnVillasMaheshwaramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/constella-villas-tukkuguda': {
      id: '/projects/constella-villas-tukkuguda'
      path: '/projects/constella-villas-tukkuguda'
      fullPath: '/projects/constella-villas-tukkuguda'
      preLoaderRoute: typeof ProjectsConstellaVillasTukkugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kavuri-forest-nest-immaguda': {
      id: '/projects/kavuri-forest-nest-immaguda'
      path: '/projects/kavuri-forest-nest-immaguda'
      fullPath: '/projects/kavuri-forest-nest-immaguda'
      preLoaderRoute: typeof ProjectsKavuriForestNestImmagudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kavuri-hills-lemon-leaf-tukkuguda': {
      id: '/projects/kavuri-hills-lemon-leaf-tukkuguda'
      path: '/projects/kavuri-hills-lemon-leaf-tukkuguda'
      fullPath: '/projects/kavuri-hills-lemon-leaf-tukkuguda'
      preLoaderRoute: typeof ProjectsKavuriHillsLemonLeafTukkugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/riddhi-laxman-county-tukkuguda': {
      id: '/projects/riddhi-laxman-county-tukkuguda'
      path: '/projects/riddhi-laxman-county-tukkuguda'
      fullPath: '/projects/riddhi-laxman-county-tukkuguda'
      preLoaderRoute: typeof ProjectsRiddhiLaxmanCountyTukkugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vertex-florenza-tukkuguda': {
      id: '/projects/vertex-florenza-tukkuguda'
      path: '/projects/vertex-florenza-tukkuguda'
      fullPath: '/projects/vertex-florenza-tukkuguda'
      preLoaderRoute: typeof ProjectsVertexFlorenzaTukkugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vertex-viva-calista-tukkuguda': {
      id: '/projects/vertex-viva-calista-tukkuguda'
      path: '/projects/vertex-viva-calista-tukkuguda'
      fullPath: '/projects/vertex-viva-calista-tukkuguda'
      preLoaderRoute: typeof ProjectsVertexVivaCalistaTukkugudaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsAnvayAvillasKongaraKalanRoute: ProjectsAnvayAvillasKongaraKalanRoute,
  ProjectsAutumnVillasMaheshwaramRoute: ProjectsAutumnVillasMaheshwaramRoute,
  ProjectsConstellaVillasTukkugudaRoute: ProjectsConstellaVillasTukkugudaRoute,
  ProjectsKavuriForestNestImmagudaRoute: ProjectsKavuriForestNestImmagudaRoute,
  ProjectsKavuriHillsLemonLeafTukkugudaRoute:
    ProjectsKavuriHillsLemonLeafTukkugudaRoute,
  ProjectsRiddhiLaxmanCountyTukkugudaRoute:
    ProjectsRiddhiLaxmanCountyTukkugudaRoute,
  ProjectsVertexFlorenzaTukkugudaRoute: ProjectsVertexFlorenzaTukkugudaRoute,
  ProjectsVertexVivaCalistaTukkugudaRoute:
    ProjectsVertexVivaCalistaTukkugudaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
